"""Derive Dark Triad feature scaling from the released CIKM 2016 dataset. stdlib only.

The historical word weights are elastic-net coefficients of standardized word2vec cluster
features (see docs/research.md). This reads the 491 released users' cluster fractions and
unigram frequencies from darktriad.tar.gz (checksum-verified, never extracted), identifies
the dataset cluster of each set of words that share a weight, and writes each cluster's
mean and population standard deviation to data/darktriad-scaling.json. import-data.py
applies them; this script is only needed to regenerate that file.

Usage: python3 scripts/derive-darktriad-scaling.py path/to/darktriad.tar.gz
"""
import argparse
import hashlib
import io
import json
import math
from pathlib import Path
import tarfile
import urllib.request

root = Path(__file__).resolve().parents[1]
manifest = json.loads((root / 'data/provenance.json').read_text())
parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument('archive', type=Path)
args = parser.parse_args()

dataset = next(e for e in manifest['sources'] if e.get('file') == 'darktriad.tar.gz')
content = args.archive.read_bytes()
if hashlib.sha256(content).hexdigest() != dataset['sha256']:
    raise ValueError(f'Checksum mismatch for {args.archive}')
entry = next(e for e in manifest['sources'] if e.get('repository') == 'phughesmcr/darktriad' and e['path'] == 'data/lexicon.json')
with urllib.request.urlopen(f"https://raw.githubusercontent.com/{entry['repository']}/{entry['commit']}/{entry['path']}", timeout=30) as response:
    lexicon_bytes = response.read()
if hashlib.sha256(lexicon_bytes).hexdigest() != entry['sha256']:
    raise ValueError('Checksum mismatch for the Dark Triad lexicon')
lexicon = json.loads(lexicon_bytes)

def table(name):
    """Space-separated user table: header row of feature names, then one row per user."""
    with tarfile.open(fileobj=io.BytesIO(content)) as archive:
        lines = archive.extractfile(f'darktriad/{name}').read().decode('utf-8').splitlines()
    header = lines[0].split(' ')[1:]
    rows = [line.split(' ') for line in lines[1:] if line.strip()]
    return header, [row[0] for row in rows], [[float(v) for v in row[1:]] for row in rows]

words, users, unigrams = table('features-unigrams')
cluster_ids, cluster_users, fractions = table('features-w2v-200')
if users != cluster_users:
    raise ValueError('Unigram and cluster tables list different users')
column = {word: j for j, word in enumerate(words)}
columns = list(zip(*fractions))

def mean(values):
    return sum(values) / len(values)

def sd(values):  # population SD, as scikit-learn's StandardScaler
    m = mean(values)
    return math.sqrt(sum((v - m) ** 2 for v in values) / len(values))

def correlation(a, b):
    ma, mb = mean(a), mean(b)
    num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    return num / math.sqrt(sum((x - ma) ** 2 for x in a) * sum((y - mb) ** 2 for y in b))

# Each cluster's words share one weight per trait; clusters are disjoint, so the same word
# sets recur across traits and the alphabetically first word identifies each set.
word_sets = {}
for terms in lexicon.values():
    groups = {}
    for term, weight in terms.items():
        groups.setdefault(weight, set()).add(term)
    for group in groups.values():
        word_sets.setdefault(min(group), frozenset(group))
clusters, unmapped = [], []
for anchor, group in sorted(word_sets.items()):
    indices = [column[w] for w in group if w in column]
    if not indices:
        unmapped.append({'anchor': anchor, 'words': len(group)})
        continue
    # A user's frequency of the cluster's common words cannot exceed the cluster fraction,
    # which also counts its rare words; the matching cluster correlates best among the rest.
    proxy = [sum(row[j] for j in indices) for row in unigrams]
    candidates = [
        (correlation(proxy, values), cluster)
        for cluster, values in zip(cluster_ids, columns)
        if all(v >= p * (1 - 1e-4) - 1e-9 for v, p in zip(values, proxy))
    ]
    r, cluster = max(candidates)
    values = columns[cluster_ids.index(cluster)]
    clusters.append({
        'cluster': cluster, 'anchor': anchor, 'words': len(group), 'wordsInUnigramTable': len(indices),
        'r': round(r, 4), 'mean': mean(values), 'sd': sd(values),
    })
if len({c['cluster'] for c in clusters}) != len(clusters):
    raise ValueError('Two word sets matched the same cluster')
output = {
    'description': 'Means and population standard deviations of the CIKM 2016 Dark Triad dataset\'s word2vec cluster fractions over its 491 users, for the clusters of the historical Dark Triad lexicon. Generated by scripts/derive-darktriad-scaling.py; see docs/research.md.',
    'source': {'file': dataset['file'], 'sha256': dataset['sha256']},
    'clusters': clusters,
    'unmapped': unmapped,
}
target = root / 'data/darktriad-scaling.json'
target.write_text(json.dumps(output, ensure_ascii=False, indent=2) + '\n')
print(f'Wrote {target}: {len(clusters)} clusters, {len(unmapped)} without words in the unigram table')
